[package]
name = "hyper-video-client-simulator"
version = "0.1.0"
authors = ["Hyper <info@hyper.video>"]
edition = "2021"
repository = "https://github.com/hypervideo/hyper.video"

[dependencies]
chrono = "0.4.40"
clap = { version = "4.5.37", features = ["derive", "env"] }
color-eyre = "0.6.3"
crossterm = "0.28.1"
dirs = "6.0.0"
eyre = "0.6.12"
futures = "0.3.31"
playwright = "0.0.20"
ratatui = "0.29.0"
scopeguard = "1.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.44.2", default-features = false, features = ["macros", "rt-multi-thread", "sync"] }
tracing = { version = "0.1.41" }
tracing-appender = "0.2"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "registry", "fmt"] }
which = "7.0.3"
